### ISSUE TITLE
NFC服务异常

### ISSUE THREAD

**Issue by jin1ming** [mrchi/magisk-miui-eu-install-mipay#2]
您好，我尝试了release的文件以及，自己提取进行封装，都在打开交通卡的时候出现了NFC服务异常
我的手机是小米10 lite room，请问这个有可解决的方法吗

**Comment by mrchi** [comment]
MIUI 的 NFC 设置中记得有一个修复选项，你试试

**Comment by jin1ming** [comment]
这个我试过了 并且也试过各种重启 然而都没帮助

**Comment by mrchi** [comment]
抱歉啊，我爱莫能助了。我的手机目前在做主力开发机使用，不方便刷机，没有办法复现您说的情况。

或者您用原作者的最新包试试看，链接是 https://blog.minamigo.moe/archives/184
